version: 2
builds:
  - main: ./cmd/gyroscope
    binary: gyroscope
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^Merge '
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.*$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\(.+\))??!?:.*$'
      order: 1
    - title: CI & build
      regexp: '^.*?(ci|build|perf|refactor)(\(.+\))??!?:.*$'
      order: 2
    - title: Others
      order: 999
